version: "3.1"

services:
  nginx:
    container_name: nginx_latest
    build: .docker/nginx
    volumes:
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes_from:
      - php

  php:
    container_name: php-7.4
    build: .docker/php
    volumes:
      - ./www:/var/www/

  db:
    container_name: mysql_latest
    build: .docker/mysql
    restart: always
    volumes:
      - database:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
    environment:
      - MYSQL_USER=userdb
      - MYSQL_ROOT_PASSWORD=07112010
      - MYSQL_PASSWORD=07112010
      - MYSQL_DATABASE=userdb
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8082:80"
    environment:
      - MYSQL_ROOT_PASSWORD=07112010
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=07112010
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M

  composer:
    image: library/composer:latest
    command: install
    volumes:
      - ./:/composer

volumes:
  database:
